# Generated by Django 4.0.5 on 2022-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captions', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
